/* ================= PIXEL ICONS ================= */
const IPAL={k:'#000000',w:'#ffffff',l:'#c0c0c0',g:'#808080',d:'#404040',b:'#1f5aa8',c:'#6bb8e8',
  n:'#02007e',G:'#2f6b3a',H:'#57a05f',M:'#8ef0b2',r:'#a02020',R:'#d24b3a',y:'#b8860b',Y:'#e8c060',
  o:'#c87020',m:'#6b4a2a',t:'#0d6b5f',s:'#d8b088',
  /* as duas do Kaki+, pra bater com o banner do forum */
  q:'#2ec4c4',p:'#ff7fb0',
  /* cores novas, so pros icones de perfil — as antigas ficam como estavam */
  v:'#7a3fa8',V:'#c08ee0',z:'#3a3a5a',Z:'#8890b0',f:'#f08030',F:'#ffd24a',e:'#f0d8a8'};
const ICONS={
mail:["                ","  kkkkkkkkkkkk  ","  kwwwwwwwwwwk  ","  kwkkwwwwkkwk  ","  kwwkkwwkkwwk  ","  kwwwkkkkwwwk  ","  kwwwwkkwwwwk  ","  kwwwwwwwwwwk  ","  kwwwwwwwwwwk  ","  kwwwwwwwwwwk  ","  kwwwwwwwwwwk  ","  kkkkkkkkkkkk  ","                ","                ","                ","                "],
mailn:["                ","  kkkkkkkkkkkk  ","  kwwwwwwwwwwk  ","  kwkkwwwwkkwk  ","  kwwkkwwkkwwk  ","  kwwwkkkkwwwk  ","  kwwwwkkwwwwk  ","  kwwwwwwwwwwk  ","  kwwwwwwwwRRk  ","  kwwwwwwwRRRR  ","  kwwwwwwwwRRk  ","  kkkkkkkkkkkk  ","                ","                ","                ","                "],
kaki:["                ","  kkkkkkkkkkkk  "," kkqqqqqqqqqqkk "," knnnnnnnnnYnnk "," knnnnnnnnYYYnk "," knwwnnwwYYYYYk "," knwwnwwnnYYYnk "," knwwwwnnnnYnnk "," knwwwnnnnnnnnk "," knwwwwnnnnnnnk "," knwwnwwnnnnnnk "," knwwnnwwnnnnnk "," knnnnnnnnnnnnk "," kknnnnnnnnnnkk ","  kkkkkkkkkkkk  ","                "],
globe:["                ","     kkkkkk     ","   kkccccbckk   ","  kcccbcccbbck  "," kccbcccbbbbbck "," kcbcccccbbbbck ","kccccbbcccbbbbck","kcbbbbcccbbbbbck","kcbbbbcccbbbbbck","kccccbbcccbbbbck"," kcbcccccbbbbck "," kccbcccbbbbbck ","  kcccbcccbbck  ","   kkccccbckk   ","     kkkkkk     ","                "],
market:["                ","  kkkkkkkkkkkk  ","  kRRRRRRRRRRk  ","  kRwwRRwwRRRk  ","  kkkkkkkkkkkk  ","  klllllllllk   ","  klwwwwwwwwlk  ","  klwkkkkkkwlk  ","  klwkGGGGkwlk  ","  klwkGMMGkwlk  ","  klwkGGGGkwlk  ","  klwkkkkkkwlk  ","  kllllllllllk  ","  kkkkkkkkkkkk  ","                ","                "],
wallet:["                ","   kkkkkkkkkk   ","   kMMMMMMMMk   ","  kkkkkkkkkkkk  ","  kmmmmmmmmmmk  ","  kmmmmmmmmmmk  ","  kmmmmmmmmmmk  ","  kmmmmkkkkmmk  ","  kmmmkYYYYkmk  ","  kmmmkYkkYkmk  ","  kmmmkYYYYkmk  ","  kmmmmkkkkmmk  ","  kmmmmmmmmmmk  ","  kkkkkkkkkkkk  ","                ","                "],
vault:["                ","  kkkkkkkkkkkk  ","  kggggggggggk  ","  kgllllllllgk  ","  kglkkkkkklgk  ","  kglkgYYgklgk  ","  kglkYkkYklgk  ","  kglkYkkYklgk  ","  kglkgYYgklgk  ","  kglkkkkkklgk  ","  kgllllllllgk  ","  kggggggggggk  ","  kkkkkkkkkkkk  ","                ","                ","                "],
gift:["    k      k    ","   kRk    kRk   ","    kRkkkkRk    ","  kkkkkkkkkkkk  ","  kHHHHkkHHHHk  ","  kHHHHkkHHHHk  ","  kkkkkkkkkkkk  ","  kMMMMkkMMMMk  ","  kMMMMkkMMMMk  ","  kMMMMkkMMMMk  ","  kMMMMkkMMMMk  ","  kMMMMkkMMMMk  ","  kkkkkkkkkkkk  ","                ","                ","                "],
kaiju:["  k          k  ","  kk        kk  ","  kGk      kGk  ","  kGGkkkkkkGGk  ","  kGGGGGGGGGGk  ","  kGkRkGGkRkGk  ","  kGGGGGGGGGGk  ","  kGkwwwwwwkGk  ","  kGkwkwkwkkGk  ","  kGGkkkkkkGGk  ","  kkGGGGGGGGkk  ","    kkkkkkkk    ","                ","                ","                ","                "],
notepad:["                ","   kkkkkkkkkk   ","   kwwwwwwwwk   ","   kwkkkkkwwk   ","   kwwwwwwwwk   ","   kwkkkkkkwk   ","   kwwwwwwwwk   ","   kwkkkkkwwk   ","   kwwwwwwwwk   ","   kwkkkkkkwk   ","   kwwwwwwwwk   ","   kkkkkkkkkk   ","                ","                ","                ","                "],
bin:["                ","     kkkkkk     ","  kkkkkkkkkkkk  ","  kkkkkkkkkkkk  ","   ktttttttt k  ","   ktkttkttk k  ","   ktkttkttk k  ","   ktkttkttk k  ","   ktkttkttk k  ","   ktkttkttk k  ","    ktttttt k   ","    kkkkkkk     ","                ","                ","                ","                "],
pc:["                ","  kkkkkkkkkkkk  ","  kllllllllllk  ","  klcccccccclk  ","  klcccccccclk  ","  klcccccccclk  ","  klcccccccclk  ","  klcccccccclk  ","  kllllllllllk  ","  kkkkkkkkkkkk  ","      kkkk      ","   kkkkkkkkkk   ","   klllllllk    ","   kkkkkkkkkk   ","                ","                "],
coin:["                ","     kkkkkk     ","   kkYYYYYYkk   ","  kYYYYyyYYYYk  "," kYYYyyyyyyYYYk "," kYYyykyykyyYYk "," kYYyykyyyyyYYk "," kYYyykyykyyYYk "," kYYYyyyyyyYYYk ","  kYYYYyyYYYYk  ","   kkYYYYYYkk   ","     kkkkkk     ","                ","                ","                ","                "],
warn:["                ","       kk       ","      krrk      ","      krrk      ","     krrrrk     ","     krwwrk     ","    krrwwrrk    ","    krrwwrrk    ","   krrrwwrrrk   ","   krrrwwrrrk   ","  krrrrrrrrrrk  ","  krrrrwwrrrrk  ","  krrrrrrrrrrk  ","  kkkkkkkkkkkk  ","                ","                "],
info:["                ","     kkkkkk     ","   kkbbbbbbkk   ","  kbbbbwwbbbbk  "," kbbbbbwwbbbbbk "," kbbbbbbbbbbbbk "," kbbbbwwwbbbbbk "," kbbbbbwwbbbbbk "," kbbbbbwwbbbbbk ","  kbbbbwwwwbbk  ","   kkbbbbbbkk   ","     kkkkkk     ","                ","                ","                ","                "],
chart:["                ","  kkkkkkkkkkkk  ","  kwwwwwwwwwwk  ","  kwwwwwwwGwwk  ","  kwwwwwwGGwwk  ","  kwwwwGGGGwwk  ","  kwwwGGGGGGwk  ","  kwGGGGGGGGwk  ","  kwGwGGGGGGwk  ","  kwGwGwGGGGwk  ","  kwGwGwGwGGwk  ","  kwwwwwwwwwwk  ","  kkkkkkkkkkkk  ","                ","                ","                "],
binder:["                ","  kkkkkkkkkkkk  ","  kbbbkllllllk  ","  kbkbkllllllk  ","  kbbbkllllllk  ","  kbkbkllllllk  ","  kbbbkllllllk  ","  kbkbkllllllk  ","  kbbbkllllllk  ","  kbkbkllllllk  ","  kbbbkllllllk  ","  kbbbkllllllk  ","  kkkkkkkkkkkk  ","                ","                ","                "],
xerr:["                ","     kkkkkk     ","   kkrrrrrrkk   ","  krrrrrrrrrrk  "," krrwwrrrrwwrrk "," krrrwwrrwwrrrk "," krrrrwwwwrrrrk "," krrrrrwwrrrrrk "," krrrrwwwwrrrrk "," krrrwwrrwwrrrk "," krrwwrrrrwwrrk ","  krrrrrrrrrrk  ","   kkrrrrrrkk   ","     kkkkkk     ","                ","                "],
music:["     kkkkkkk    ","     kbbbbbbk   ","     kbkkkkbk   ","     kbk  kbk   ","     kbk  kbk   ","     kbk  kbk   ","     kbk  kbk   ","   kkkbk  kbk   ","  kbbbbk  kbk   ","  kbbbbk kkbkk  ","  kbbbbk kbbbk  ","   kkkk  kbbbk  ","         kkkkk  ","                ","                ","                "],
fire:["                ","       kk       ","      koRk      ","     koRRk      ","     koRRRk     ","    koRRRRk     ","    koRRRRRk    ","   koRRRoRRRk   ","   koRRRoRRRk   ","   koRRRRRRRk   ","   kkoRRRRRok   ","    kkoRRRok    ","     kkoook     ","      kkkk      ","                ","                "],
power:["                ","     kkkkkk     ","   kkllddllkk   ","  kllddddddldk  ","  kldddRRddddk  "," klddRdRRdRdddk "," kldRddRRddRddk "," kddRddddddRddk "," kddRddddddRddk "," kldRddddddRddk "," klddRddddRdddk ","  klddRRRRdddk  ","  kddddddddddk  ","   kkddddddkk   ","     kkkkkk     ","                "],
chat:["                ","  kkkkkkkkkkkk  ","  kwwwwwwwwwwk  ","  kwkkkwwkkkwk  ","  kwwwwwwwwwwk  ","  kwkkkkkkkwwk  ","  kwwwwwwwwwwk  ","  kwkkkkkwwwwk  ","  kwwwwwwwwwwk  ","  kkkkkkkkkkkk  ","     kwwk       ","      kwk       ","       kk       ","                ","                ","                "],
star:["                ","       kk       ","      kYYk      ","      kYYk      ","     kYYYYk     ","kkkkkkYYYYkkkkkk","kYYYYYYYYYYYYYYk","kyYYYYYYYYYYYYyk"," kyyYYYYYYYYyyk ","  kyyYYYYYYyyk  ","   kyYYYYYYyk   ","  kyYYYkkYYYyk  "," kyYYYk  kYYYyk ","kyYYyk    kyYYyk","kykk        kkyk","                "],
rocket:["      kkkk      ","     kwwwwk     ","    kwRRRRwk    ","    kwRccRwk    ","    kwRccRwk    ","   kkwRRRRwkk   ","  kRkwwwwwwkRk  ","  kRRkwwwwkRRk  ","  kRRkwwwwkRRk  ","   kkwwwwwwkk   ","    kwwwwwwk    ","     kYYYYk     ","      kYYk      ","       kk       ","                ","                "]
,
/* ================= FOTOS DE PERFIL DO KAKI+ =================
   O forum tinha uma pessoa so com a cara verde do Kaiju: whoIco() devolvia
   'kaiju' pra todo mundo que nao fosse do elenco fixo. Agora sao cinquenta
   objetos (tralha de mesa de 1999, bicho, cara) mais o alfabeto inteiro, e o
   hash do nick escolhe sempre o mesmo pra mesma pessoa.
   REGRA: toda grade tem 16 linhas de 16 caracteres. Fora disso vira lixo. */
floppy:["                "," kkkkkkkkkkkkkk "," kbbbbbbbbbbbbk "," kbbkkkkkkkkbbk "," kbbkwwwwwwkbbk "," kbbkwwkkwwkbbk "," kbbkwwkkwwkbbk "," kbbkkkkkkkkbbk "," kbbbbbbbbbbbbk "," kbbbbbbbbbbbbk "," kbkkkkkkkkkkbk "," kbkwwwwwwwwkbk "," kbkwkkkkkkwkbk "," kbkwwwwwwwwkbk "," kkkkkkkkkkkkkk ","                "],
cd:["                ","     kkkkkk     ","   kkllllllkk   ","  kllllllllllk  "," kllllwwwwllllk "," kllwwwwwwwwllk ","kllwwwwkkwwwwllk","kllwwwkkkkwwwllk","kllwwwkkkkwwwllk","kllwwwwkkwwwwllk"," kllwwwwwwwwllk "," kllllwwwwllllk ","  kllllllllllk  ","   kkllllllkk   ","     kkkkkk     ","                "],
mug:["                ","                ","   kkkkkkkkk    ","   kwwwwwwwk    ","   kwmmmmmwkkk  ","   kwmmmmmwklk  ","   kwmmmmmwklk  ","   kwmmmmmwklk  ","   kwmmmmmwkkk  ","   kwmmmmmwk    ","   kwmmmmmwk    ","   kwwwwwwwk    ","    kkkkkkk     ","                ","                ","                "],
tape:["                ","                ","  kkkkkkkkkkkk  ","  kddddddddddk  ","  kdkkkkkkkkdk  ","  kdklllllllkd  ","  kdkkkkkkkkdk  ","  kddkwwkwwkddk ","  kddkwwkwwkddk ","  kddkkkkkkddk  ","  kddddddddddk  ","  kdkddddddkdk  ","  kkkkkkkkkkkk  ","                ","                ","                "],
tv:["                ","     k    k     ","      k  k      ","       kk       ","  kkkkkkkkkkkk  ","  kllllllllllk  ","  klcccccccclk  ","  klcccccccclk  ","  klcccccccclk  ","  klcccccccclk  ","  kllllllllllk  ","  kkkkkkkkkkkk  ","   kk      kk   ","                ","                ","                "],
phone:["                ","  kkkk    kkkk  "," kdddk    kdddk "," kdddk    kdddk "," kdddkkkkkkdddk "," kddddddddddddk "," kkddddddddddkk ","  kkddddddddkk  ","   kkkkkkkkkk   ","                ","                ","                ","                ","                ","                ","                "],
cam:["                ","      kkkk      ","    kkkkkkkk    ","  kkkkkkkkkkkk  ","  kddddddddddk  ","  kddkkkkkkddk  ","  kdkllllllkdk  ","  kdklcccclkdk  ","  kdklcccclkdk  ","  kdkllllllkdk  ","  kddkkkkkkddk  ","  kddddddddddk  ","  kkkkkkkkkkkk  ","                ","                ","                "],
book:["                ","  kkkkkkkkkkkk  ","  kRRRRkkRRRRk  ","  kRwwRkkRwwRk  ","  kRwwRkkRwwRk  ","  kRwwRkkRwwRk  ","  kRwwRkkRwwRk  ","  kRwwRkkRwwRk  ","  kRwwRkkRwwRk  ","  kRwwRkkRwwRk  ","  kRRRRkkRRRRk  ","  kkkkkkkkkkkk  ","                ","                ","                ","                "],
pencil:["                ","            kkk ","           kYYk ","          kYYYk ","         kYYYk  ","        kYYYk   ","       kYYYk    ","      kYYYk     ","     kYYYk      ","    kYYYk       ","   kwwYk        ","  kwwwk         "," kkkkk          ","  kkk           ","                ","                "],
marker:["                ","     kkkkkk     ","     kppppk     ","     kppppk     ","    kkkkkkkk    ","    kFFFFFFk    ","    kFFFFFFk    ","    kFFFFFFk    ","    kFFFFFFk    ","    kFFFFFFk    ","    kkkkkkkk    ","     kwwwwk     ","    kwwwwwwk    ","   kFFFFFFFFk   ","   kkkkkkkkkk   ","                "],
clock:["                ","      kkkk      ","    kkkkkkkk    ","   kkwwwwwwkk   ","  kkwwwkwwwwkk  ","  kwwwwkwwwwwk  "," kwwwwwkwwwwwwk "," kwwwwwkwwwwwwk "," kwwwwwkkkkwwwk "," kwwwwwwwwwwwwk ","  kwwwwwwwwwwk  ","  kkwwwwwwwwkk  ","   kkwwwwwwkk   ","    kkkkkkkk    ","      kkkk      ","                "],
lamp:["                ","     kkkkkk     ","    kYYYYYYk    ","   kYYYYYYYYk   ","  kYYYYYYYYYYk  ","  kkkkkkkkkkkk  ","      kggk      ","      kggk      ","      kggk      ","      kggk      ","      kggk      ","     kkggkk     ","   kkgggggggkk  ","   kggggggggggk ","   kkkkkkkkkkkk ","                "],
plant:["                ","    k     k     ","   kHk   kHk    ","   kHHk kHHk    ","  kHHHHkHHHHk   ","  kHHHHHHHHHHk  ","   kHHHHHHHHk   ","     kkHHkk     ","      kHHk      ","    kkkkkkkk    ","    kooooook    ","    kooooook    ","    kooooook    ","     kooook     ","     kkkkkk     ","                "],
cat:["                ","   kk      kk   ","   kok    kok   ","   kook  kook   ","  kkoookkoookk  ","  kooooooooook  ","  kookkookkook  ","  kookkookkook  ","  kooooooooook  ","  kooooRRooook  ","  koookkkkoook  ","  kooooooooook  ","  kkooooooookk  ","   kkkkkkkkkk   ","                ","                "],
dog:["                ","   kk      kk   ","  kmmk    kmmk  ","  kmmkkkkkkmmk  ","  kmssssssssmk  ","  kmssssssssmk  ","  kmsskssksskk  ","  kmssssssssmk  ","  kmsskkkksskk  ","  kmsskkkksskk  ","  kmssssssssmk  ","  kkssssssssk   ","   kkkkkkkkkk   ","                ","                ","                "],
frog:["                ","   kkk    kkk   ","  kHwHk  kHwHk  ","  kHkHk  kHkHk  "," kkHHHkkkkHHHkk "," kHHHHHHHHHHHHk "," kHHHHHHHHHHHHk "," kHHkkkkkkkkHHk "," kHHHHHHHHHHHHk ","  kHHHHHHHHHHk  ","  kkHHHHHHHHkk  "," kkHkkkkkkkkHkk "," kHHk      kHHk "," kkkk      kkkk ","                ","                "],
ghost:["                ","     kkkkkk     ","   kkwwwwwwkk   ","  kwwwwwwwwwwk  ","  kwwkkwwkkwwk  ","  kwwkkwwkkwwk  ","  kwwwwwwwwwwk  ","  kwwwwwwwwwwk  ","  kwwwkkkkwwwk  ","  kwwwwwwwwwwk  ","  kwwwwwwwwwwk  ","  kwwwwwwwwwwk  ","  kwkwwkkwwkwk  ","  kkkkkkkkkkkk  ","                ","                "],
skull:["                ","    kkkkkkkk    ","   kwwwwwwwwk   ","  kwwwwwwwwwwk  ","  kwkkwwwwkkwk  ","  kwkkwwwwkkwk  ","  kwwwwwwwwwwk  ","  kwwwwkkwwwwk  ","  kwwwwkkwwwwk  ","   kwwwwwwwwk   ","   kwkwkwkwwk   ","   kwkwkwkwwk   ","   kkkkkkkkkk   ","                ","                ","                "],
robot:["                ","       kk       ","      kllk      ","  kkkkkkkkkkkk  ","  klllllllllk   ","  klkkllllkklk  ","  klkclllckklk  ","  kllllllllllk  ","  kllkkkkkkllk  ","  kllllllllllk  ","  kkkkkkkkkkkk  ","   kllk  kllk   ","   kllk  kllk   ","   kkkk  kkkk   ","                ","                "],
alien:["                ","    kkkkkkkk    ","  kkHHHHHHHHkk  "," kHHHHHHHHHHHHk "," kHHHHHHHHHHHHk "," kHkkkHHHHkkkHk "," kHkkkHHHHkkkHk "," kHHHHHHHHHHHHk ","  kHHHHHHHHHHk  ","   kHHkkkkHHk   ","    kHHHHHHk    ","     kHkkHk     ","      kkkk      ","                ","                ","                "],
bug:["                ","   k        k   ","    kk    kk    ","     kkkkkk     ","   kkRRRRRRkk   ","  kRRkRRRRkRRk  ","  kRRRRRRRRRRk  "," kkRRkRRRRkRRkk "," kRRRRRRRRRRRRk "," kkRRkRRRRkRRkk ","  kRRRRRRRRRRk  ","  kRRkRRRRkRRk  ","   kkRRRRRRkk   ","     kkkkkk     ","                ","                "],
fish:["                ","                ","          kkk   ","   kkkk  kkck   ","  kcccckkcccck  "," kccwkcccccccck ","kcccccccccccck  "," kccccccccccck  ","  kcccckkcccck  ","   kkkk  kkck   ","          kkk   ","                ","                ","                ","                ","                "],
bird:["                ","                ","     kkkk       ","   kkbbbbkk     ","  kbbwkbbbbk    ","  kbbbbbbbbkYk  ","  kbwwwwwwbkYk  "," kbwwwwwwwwbk   "," kbbwwwwwwbk    ","  kbbbbbbbk     ","   kbbbbbk      ","    kkkkk       ","    k   k       ","   kk   kk      ","                ","                "],
moon:["                ","     kkkkk      ","   kkYYYYYkk    ","  kYYYYYkkkk    ","  kYYYYkk       "," kYYYYkk        "," kYYYYk         "," kYYYYk         "," kYYYYk         "," kYYYYkk        ","  kYYYYkk       ","  kYYYYYkkkk    ","   kkYYYYYkk    ","     kkkkk      ","                ","                "],
sun:["                ","      kkk       ","   k  kYk  k    ","    k kYk k     ","     kkYkk      ","  kkkYYYYYkkk   ","  kYYYYYYYYYk   ","  kkYYYYYYYkk   ","  kkYYYYYYYkk   ","  kYYYYYYYYYk   ","  kkkYYYYYkkk   ","     kkYkk      ","    k kYk k     ","   k  kkk  k    ","                ","                "],
cloud:["                ","                ","      kkkk      ","    kkwwwwkk    ","   kwwwwwwwwk   ","  kkwwwwwwwwkk  "," kwwwwwwwwwwwwk "," kwwwwwwwwwwwwk "," kkkkkkkkkkkkk  ","   k   k   k    ","   k   k   k    ","    k   k   k   ","                ","                ","                ","                "],
umbrella:["                ","       kk       ","     kkRRkk     ","   kkRRRRRRkk   ","  kRRRRRRRRRRk  "," kRRRRRRRRRRRRk ","kRkRRkRRkRRkRRk ","kkkkkkkkkkkkkkk ","       kk       ","       kk       ","       kk       ","       kk       ","     kkkk       ","     kwwk       ","     kkkk       ","                "],
key:["                ","    kkkk        ","   kYYYYk       ","  kYYkkYYk      ","  kYYkkYYk      ","   kYYYYk       ","    kYYk        ","    kYYk        ","    kYYk        ","    kYYkkk      ","    kYYYYk      ","    kYYkkk      ","    kYYYk       ","    kkkk        ","                ","                "],
lock:["                ","     kkkkkk     ","    kllllllk    ","   kllkkkkllk   ","   kllk  kllk   ","   kllk  kllk   "," kkkkkkkkkkkkk  "," kYYYYYYYYYYYk  "," kYYYYYkYYYYYk  "," kYYYYkkkYYYYk  "," kYYYYkkkYYYYk  "," kYYYYYkYYYYYk  "," kYYYYYYYYYYYk  "," kkkkkkkkkkkkk  ","                ","                "],
dice:["                ","  kkkkkkkkkkkk  ","  kwwwwwwwwwwk  ","  kwkkwwwwwwwk  ","  kwkkwwwwwwwk  ","  kwwwwwwwwwwk  ","  kwwwwkkwwwwk  ","  kwwwwkkwwwwk  ","  kwwwwwwwwwwk  ","  kwwwwwwwkkwk  ","  kwwwwwwwkkwk  ","  kwwwwwwwwwwk  ","  kkkkkkkkkkkk  ","                ","                ","                "],
heart:["                ","                ","   kkk    kkk   ","  kRRRkkkkRRRk  "," kRRRRRRRRRRRk  "," kRRRRRRRRRRRk  "," kRRRRRRRRRRRk  ","  kRRRRRRRRRk   ","   kRRRRRRRk    ","    kRRRRRk     ","     kRRRk      ","      kRk       ","       k        ","                ","                ","                "],
burger:["                ","                ","    kkkkkkkk    ","  kkooooooookk  "," kooooowooooook "," koooooooooooook"," kkkkkkkkkkkkkk "," kHHHHHHHHHHHHk "," kkkkkkkkkkkkkk "," kRRRRRRRRRRRRk "," kkkkkkkkkkkkkk "," koooooooooooook","  kkoooooooookk ","    kkkkkkkk    ","                ","                "],
joystick:["                ","      kkk       ","     kRRRk      ","     kRRRk      ","      kkk       ","      kdk       ","      kdk       ","  kkkkkkkkkkk   "," kllllllllllllk "," klkklllllkkllk "," kllllllllllllk "," kkkkkkkkkkkkkk ","                ","                ","                ","                "],
star2:["                ","       kk       ","      kYYk      ","      kYYk      ","     kYYYYk     "," kkkkkYYYYkkkkk "," kYYYYYYYYYYYYk ","  kYYYYYYYYYYk  ","   kYYYYYYYYk   ","   kYYYkkYYYk   ","  kYYYk  kYYYk  ","  kYk      kYk  ","                ","                ","                ","                "],
mouse:["                ","     kkkkkk     ","    kwwwwwwk    ","   kwwkddkwwk   ","   kwwkddkwwk   ","   kwwkkkkwwk   ","   kwwwwwwwwk   ","   kwwwwwwwwk   ","   kwwwwwwwwk   ","   kwwwwwwwwk   ","    kwwwwwwk    ","     kkkkkk     ","                ","                ","                ","                "],
bulb:["                ","     kkkkkk     ","   kkYYYYYYkk   ","  kYYYYYYYYYYk  ","  kYYYwwwwYYYk  ","  kYYwwwwwwYYk  ","  kYYYwwwwYYYk  ","  kYYYYwwYYYYk  ","   kYYYwwYYYk   ","    kkkkkkkk    ","    kllllllk    ","    kkkkkkkk    ","    kllllllk    ","     kkkkkk     ","                ","                "],
note2:["                ","        kkkkk   ","        kwwwk   ","        kwwwk   ","        kwwwk   ","        kwwwk   ","     kkkkwwwk   ","    kvvvkwwwk   ","    kvvvkkkkk   ","    kvvvk       ","  kkkvvvk       "," kvvvvvvk       "," kvvvvvk        ","  kkkkk         ","                ","                "],
ufo:["                ","                ","      kkkk      ","    kkccccck    ","   kcwwwwwck    ","  kkcccccccckk  "," kllllllllllllk ","kllkllkllkllkllk"," kllllllllllllk ","  kkkkkkkkkkkk  ","   kMk kMk kMk  ","    k   k   k   ","                ","                ","                ","                "],
ring:["                ","      kkkk      ","     kMMMMk     ","    kMMwwMMk    ","     kMMMMk     ","      kkkk      ","   kkkkkkkkkk   ","  kYYYYYYYYYYk  ","  kYkkkkkkkkYk  ","  kYk      kYk  ","  kYYk    kYYk  ","   kYYkkkkYYk   ","    kYYYYYYk    ","     kkkkkk     ","                ","                "],
snail:["                ","                ","                ","      kkkkk     ","    kkoooookk   ","   koookkkoook  ","  kookkwwkkook  ","  kokkwwwwkkok  ","  kokkwwwwkkok  "," kkookkwwkkookk ","kkkooookkkoookk ","kwkkoooooooookk ","kwkkkkkkkkkkkk  "," kkkk           ","                ","                "],
candle:["                ","       kk       ","      kfFk      ","      kfFk      ","       kk       ","    kkkkkkkk    ","    kwwwwwwk    ","    kwwwwwwk    ","    kwwwwwwk    ","    kwwwwwwk    ","    kwwwwwwk    ","    kwwwwwwk    ","   kkkkkkkkk    ","   kllllllllk   ","   kkkkkkkkkk   ","                "],
crown:["                ","                ","   k       k    ","  kYk kkk kYk   ","  kYk kYk kYk   ","  kYkkkYkkkYk   ","  kYYYYYYYYYk   ","  kYYYYYYYYYk   ","  kYYRYYRYYRk   ","  kYYYYYYYYYk   ","  kkkkkkkkkkk   ","                ","                ","                ","                ","                "],
mask:["                ","                ","  kkkkkkkkkkkk  "," kwwwwwwwwwwwwk "," kwkkwwwwwwkkwk "," kwkkwwwwwwkkwk "," kwwwwwwwwwwwwk "," kwwwwwkkwwwwwk ","  kwwwwwwwwwwk  ","  kkwwwwwwwwkk  ","   kkwwwwwwkk   ","    kkwwwwkk    ","     kkkkkk     ","                ","                ","                "],
rain:["                ","      kkkk      ","    kkllllkk    ","   klllllllk    ","  kkllllllllkk  "," kllllllllllllk "," kkkkkkkkkkkkk  ","   kck kck kck  ","   kck kck kck  ","    kk  kk  kk  ","  kck kck kck   ","  kck kck kck   ","   kk  kk  kk   ","                ","                ","                "],
mailbox:["                ","                ","   kkkkkkkkk    ","  kRRRRRRRRRk   "," kRRRRRRRRRRk   "," kRkkkkkkkRRk   "," kRkwwwwwkRRk   "," kRkwwwwwkRRk   "," kRkkkkkkkRRk   "," kRRRRRRRRRRk   ","  kkkkkkkkkkk   ","      kmk       ","      kmk       ","     kkkkk      ","                ","                "],
flame2:["                ","       kk       ","      kfk       ","     kffFk      ","     kfFFk      ","    kfFFFFk     ","   kfFFFFFFk    ","   kfFFwwFFk    ","  kfFFwwwwFFk   ","  kfFFwwwwFFk   ","  kfFFFwwFFFk   ","   kffFFFFfk    ","    kkfffkk     ","      kkk       ","                ","                "],
gem:["                ","                ","   kkkkkkkkkk   ","  kqqkkqqkkqqk  "," kqqqqqqqqqqqqk "," kkqqqqqqqqqqkk ","  kkqqqqqqqqkk  ","   kkqqqqqqkk   ","    kkqqqqkk    ","     kkqqkk     ","      kkkk      ","       kk       ","                ","                ","                ","                "],
crt:["                ","  kkkkkkkkkkkk  ","  kllllllllllk  ","  klkkkkkkkklk  ","  klkzzzzzzklk  ","  klkzqqqqzklk  ","  klkzqqqqzklk  ","  klkzzzzzzklk  ","  klkkkkkkkklk  ","  kllkllllkllk  ","  kkkkkkkkkkkk  ","    kkkkkkkk    ","   kllllllllk   ","   kkkkkkkkkk   ","                ","                "],
bone:["                ","                ","  kkk       kkk "," kwwwk     kwwwk"," kwwwkkkkkkkwwwk"," kwwwwwwwwwwwwwk"," kwwwkkkkkkkwwwk"," kwwwk     kwwwk","  kkk       kkk ","                ","                ","                ","                ","                ","                ","                "],
donut:["                ","     kkkkkk     ","   kkooooookk   ","  koooooooooook "," kooookkkkoooook"," koookkkkkkkoook"," kookkwwwwkkookk"," kookkwwwwkkookk"," koookkkkkkkoook"," kooookkkkoooook","  koooooooooook ","   kkooooookk   ","     kkkkkk     ","                ","                ","                "],
ltr_A:["kkkkkkkkkkkkkkkk","kbbbbwwwwwwbbbbk","kbbbbwwwwwwbbbbk","kbbwwbbbbbbwwbbk","kbbwwbbbbbbwwbbk","kbbwwbbbbbbwwbbk","kbbwwbbbbbbwwbbk","kbbwwwwwwwwwwbbk","kbbwwwwwwwwwwbbk","kbbwwbbbbbbwwbbk","kbbwwbbbbbbwwbbk","kbbwwbbbbbbwwbbk","kbbwwbbbbbbwwbbk","kbbwwbbbbbbwwbbk","kbbwwbbbbbbwwbbk","kkkkkkkkkkkkkkkk"],
ltr_B:["kkkkkkkkkkkkkkkk","knnwwwwwwwwnnnnk","knnwwwwwwwwnnnnk","knnwwnnnnnnwwnnk","knnwwnnnnnnwwnnk","knnwwnnnnnnwwnnk","knnwwnnnnnnwwnnk","knnwwwwwwwwnnnnk","knnwwwwwwwwnnnnk","knnwwnnnnnnwwnnk","knnwwnnnnnnwwnnk","knnwwnnnnnnwwnnk","knnwwnnnnnnwwnnk","knnwwwwwwwwnnnnk","knnwwwwwwwwnnnnk","kkkkkkkkkkkkkkkk"],
ltr_C:["kkkkkkkkkkkkkkkk","kGGGGwwwwwwGGGGk","kGGGGwwwwwwGGGGk","kGGwwGGGGGGwwGGk","kGGwwGGGGGGwwGGk","kGGwwGGGGGGGGGGk","kGGwwGGGGGGGGGGk","kGGwwGGGGGGGGGGk","kGGwwGGGGGGGGGGk","kGGwwGGGGGGGGGGk","kGGwwGGGGGGGGGGk","kGGwwGGGGGGwwGGk","kGGwwGGGGGGwwGGk","kGGGGwwwwwwGGGGk","kGGGGwwwwwwGGGGk","kkkkkkkkkkkkkkkk"],
ltr_D:["kkkkkkkkkkkkkkkk","krrwwwwwwwwrrrrk","krrwwwwwwwwrrrrk","krrwwrrrrrrwwrrk","krrwwrrrrrrwwrrk","krrwwrrrrrrwwrrk","krrwwrrrrrrwwrrk","krrwwrrrrrrwwrrk","krrwwrrrrrrwwrrk","krrwwrrrrrrwwrrk","krrwwrrrrrrwwrrk","krrwwrrrrrrwwrrk","krrwwrrrrrrwwrrk","krrwwwwwwwwrrrrk","krrwwwwwwwwrrrrk","kkkkkkkkkkkkkkkk"],
ltr_E:["kkkkkkkkkkkkkkkk","kvvwwwwwwwwwwvvk","kvvwwwwwwwwwwvvk","kvvwwvvvvvvvvvvk","kvvwwvvvvvvvvvvk","kvvwwvvvvvvvvvvk","kvvwwvvvvvvvvvvk","kvvwwwwwwwwvvvvk","kvvwwwwwwwwvvvvk","kvvwwvvvvvvvvvvk","kvvwwvvvvvvvvvvk","kvvwwvvvvvvvvvvk","kvvwwvvvvvvvvvvk","kvvwwwwwwwwwwvvk","kvvwwwwwwwwwwvvk","kkkkkkkkkkkkkkkk"],
ltr_F:["kkkkkkkkkkkkkkkk","kttwwwwwwwwwwttk","kttwwwwwwwwwwttk","kttwwttttttttttk","kttwwttttttttttk","kttwwttttttttttk","kttwwttttttttttk","kttwwwwwwwwttttk","kttwwwwwwwwttttk","kttwwttttttttttk","kttwwttttttttttk","kttwwttttttttttk","kttwwttttttttttk","kttwwttttttttttk","kttwwttttttttttk","kkkkkkkkkkkkkkkk"],
ltr_G:["kkkkkkkkkkkkkkkk","koooowwwwwwooook","koooowwwwwwooook","koowwoooooowwook","koowwoooooowwook","koowwooooooooook","koowwooooooooook","koowwoowwwwwwook","koowwoowwwwwwook","koowwoooooowwook","koowwoooooowwook","koowwoooooowwook","koowwoooooowwook","koooowwwwwwwwook","koooowwwwwwwwook","kkkkkkkkkkkkkkkk"],
ltr_H:["kkkkkkkkkkkkkkkk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwwwwwwwwwmmk","kmmwwwwwwwwwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kkkkkkkkkkkkkkkk"],
ltr_I:["kkkkkkkkkkkkkkkk","kzzwwwwwwwwwwzzk","kzzwwwwwwwwwwzzk","kzzzzzzwwzzzzzzk","kzzzzzzwwzzzzzzk","kzzzzzzwwzzzzzzk","kzzzzzzwwzzzzzzk","kzzzzzzwwzzzzzzk","kzzzzzzwwzzzzzzk","kzzzzzzwwzzzzzzk","kzzzzzzwwzzzzzzk","kzzzzzzwwzzzzzzk","kzzzzzzwwzzzzzzk","kzzwwwwwwwwwwzzk","kzzwwwwwwwwwwzzk","kkkkkkkkkkkkkkkk"],
ltr_J:["kkkkkkkkkkkkkkkk","kRRRRRRwwwwwwRRk","kRRRRRRwwwwwwRRk","kRRRRRRRRwwRRRRk","kRRRRRRRRwwRRRRk","kRRRRRRRRwwRRRRk","kRRRRRRRRwwRRRRk","kRRRRRRRRwwRRRRk","kRRRRRRRRwwRRRRk","kRRRRRRRRwwRRRRk","kRRRRRRRRwwRRRRk","kRRwwRRRRwwRRRRk","kRRwwRRRRwwRRRRk","kRRRRwwwwRRRRRRk","kRRRRwwwwRRRRRRk","kkkkkkkkkkkkkkkk"],
ltr_K:["kkkkkkkkkkkkkkkk","kyywwyyyyyywwyyk","kyywwyyyyyywwyyk","kyywwyyyywwyyyyk","kyywwyyyywwyyyyk","kyywwyywwyyyyyyk","kyywwyywwyyyyyyk","kyywwwwyyyyyyyyk","kyywwwwyyyyyyyyk","kyywwyywwyyyyyyk","kyywwyywwyyyyyyk","kyywwyyyywwyyyyk","kyywwyyyywwyyyyk","kyywwyyyyyywwyyk","kyywwyyyyyywwyyk","kkkkkkkkkkkkkkkk"],
ltr_L:["kkkkkkkkkkkkkkkk","kddwwddddddddddk","kddwwddddddddddk","kddwwddddddddddk","kddwwddddddddddk","kddwwddddddddddk","kddwwddddddddddk","kddwwddddddddddk","kddwwddddddddddk","kddwwddddddddddk","kddwwddddddddddk","kddwwddddddddddk","kddwwddddddddddk","kddwwwwwwwwwwddk","kddwwwwwwwwwwddk","kkkkkkkkkkkkkkkk"],
ltr_M:["kkkkkkkkkkkkkkkk","kHHwwHHHHHHwwHHk","kHHwwHHHHHHwwHHk","kHHwwwwHHwwwwHHk","kHHwwwwHHwwwwHHk","kHHwwHHwwHHwwHHk","kHHwwHHwwHHwwHHk","kHHwwHHwwHHwwHHk","kHHwwHHwwHHwwHHk","kHHwwHHHHHHwwHHk","kHHwwHHHHHHwwHHk","kHHwwHHHHHHwwHHk","kHHwwHHHHHHwwHHk","kHHwwHHHHHHwwHHk","kHHwwHHHHHHwwHHk","kkkkkkkkkkkkkkkk"],
ltr_N:["kkkkkkkkkkkkkkkk","kbbwwbbbbbbwwbbk","kbbwwbbbbbbwwbbk","kbbwwwwbbbbwwbbk","kbbwwwwbbbbwwbbk","kbbwwbbwwbbwwbbk","kbbwwbbwwbbwwbbk","kbbwwbbbbwwwwbbk","kbbwwbbbbwwwwbbk","kbbwwbbbbbbwwbbk","kbbwwbbbbbbwwbbk","kbbwwbbbbbbwwbbk","kbbwwbbbbbbwwbbk","kbbwwbbbbbbwwbbk","kbbwwbbbbbbwwbbk","kkkkkkkkkkkkkkkk"],
ltr_O:["kkkkkkkkkkkkkkkk","knnnnwwwwwwnnnnk","knnnnwwwwwwnnnnk","knnwwnnnnnnwwnnk","knnwwnnnnnnwwnnk","knnwwnnnnnnwwnnk","knnwwnnnnnnwwnnk","knnwwnnnnnnwwnnk","knnwwnnnnnnwwnnk","knnwwnnnnnnwwnnk","knnwwnnnnnnwwnnk","knnwwnnnnnnwwnnk","knnwwnnnnnnwwnnk","knnnnwwwwwwnnnnk","knnnnwwwwwwnnnnk","kkkkkkkkkkkkkkkk"],
ltr_P:["kkkkkkkkkkkkkkkk","kGGwwwwwwwwGGGGk","kGGwwwwwwwwGGGGk","kGGwwGGGGGGwwGGk","kGGwwGGGGGGwwGGk","kGGwwGGGGGGwwGGk","kGGwwGGGGGGwwGGk","kGGwwwwwwwwGGGGk","kGGwwwwwwwwGGGGk","kGGwwGGGGGGGGGGk","kGGwwGGGGGGGGGGk","kGGwwGGGGGGGGGGk","kGGwwGGGGGGGGGGk","kGGwwGGGGGGGGGGk","kGGwwGGGGGGGGGGk","kkkkkkkkkkkkkkkk"],
ltr_Q:["kkkkkkkkkkkkkkkk","krrrrwwwwwwrrrrk","krrrrwwwwwwrrrrk","krrwwrrrrrrwwrrk","krrwwrrrrrrwwrrk","krrwwrrrrrrwwrrk","krrwwrrrrrrwwrrk","krrwwrrrrrrwwrrk","krrwwrrrrrrwwrrk","krrwwrrwwrrwwrrk","krrwwrrwwrrwwrrk","krrwwrrrrwwrrrrk","krrwwrrrrwwrrrrk","krrrrwwwwrrwwrrk","krrrrwwwwrrwwrrk","kkkkkkkkkkkkkkkk"],
ltr_R:["kkkkkkkkkkkkkkkk","kvvwwwwwwwwvvvvk","kvvwwwwwwwwvvvvk","kvvwwvvvvvvwwvvk","kvvwwvvvvvvwwvvk","kvvwwvvvvvvwwvvk","kvvwwvvvvvvwwvvk","kvvwwwwwwwwvvvvk","kvvwwwwwwwwvvvvk","kvvwwvvwwvvvvvvk","kvvwwvvwwvvvvvvk","kvvwwvvvvwwvvvvk","kvvwwvvvvwwvvvvk","kvvwwvvvvvvwwvvk","kvvwwvvvvvvwwvvk","kkkkkkkkkkkkkkkk"],
ltr_S:["kkkkkkkkkkkkkkkk","kttttwwwwwwwwttk","kttttwwwwwwwwttk","kttwwttttttttttk","kttwwttttttttttk","kttwwttttttttttk","kttwwttttttttttk","kttttwwwwwwttttk","kttttwwwwwwttttk","kttttttttttwwttk","kttttttttttwwttk","kttttttttttwwttk","kttttttttttwwttk","kttwwwwwwwwttttk","kttwwwwwwwwttttk","kkkkkkkkkkkkkkkk"],
ltr_T:["kkkkkkkkkkkkkkkk","koowwwwwwwwwwook","koowwwwwwwwwwook","koooooowwooooook","koooooowwooooook","koooooowwooooook","koooooowwooooook","koooooowwooooook","koooooowwooooook","koooooowwooooook","koooooowwooooook","koooooowwooooook","koooooowwooooook","koooooowwooooook","koooooowwooooook","kkkkkkkkkkkkkkkk"],
ltr_U:["kkkkkkkkkkkkkkkk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmwwmmmmmmwwmmk","kmmmmwwwwwwmmmmk","kmmmmwwwwwwmmmmk","kkkkkkkkkkkkkkkk"],
ltr_V:["kkkkkkkkkkkkkkkk","kzzwwzzzzzzwwzzk","kzzwwzzzzzzwwzzk","kzzwwzzzzzzwwzzk","kzzwwzzzzzzwwzzk","kzzwwzzzzzzwwzzk","kzzwwzzzzzzwwzzk","kzzwwzzzzzzwwzzk","kzzwwzzzzzzwwzzk","kzzwwzzzzzzwwzzk","kzzwwzzzzzzwwzzk","kzzzzwwzzwwzzzzk","kzzzzwwzzwwzzzzk","kzzzzzzwwzzzzzzk","kzzzzzzwwzzzzzzk","kkkkkkkkkkkkkkkk"],
ltr_W:["kkkkkkkkkkkkkkkk","kRRwwRRRRRRwwRRk","kRRwwRRRRRRwwRRk","kRRwwRRRRRRwwRRk","kRRwwRRRRRRwwRRk","kRRwwRRRRRRwwRRk","kRRwwRRRRRRwwRRk","kRRwwRRwwRRwwRRk","kRRwwRRwwRRwwRRk","kRRwwRRwwRRwwRRk","kRRwwRRwwRRwwRRk","kRRwwwwRRwwwwRRk","kRRwwwwRRwwwwRRk","kRRwwRRRRRRwwRRk","kRRwwRRRRRRwwRRk","kkkkkkkkkkkkkkkk"],
ltr_X:["kkkkkkkkkkkkkkkk","kyywwyyyyyywwyyk","kyywwyyyyyywwyyk","kyywwyyyyyywwyyk","kyywwyyyyyywwyyk","kyyyywwyywwyyyyk","kyyyywwyywwyyyyk","kyyyyyywwyyyyyyk","kyyyyyywwyyyyyyk","kyyyywwyywwyyyyk","kyyyywwyywwyyyyk","kyywwyyyyyywwyyk","kyywwyyyyyywwyyk","kyywwyyyyyywwyyk","kyywwyyyyyywwyyk","kkkkkkkkkkkkkkkk"],
ltr_Y:["kkkkkkkkkkkkkkkk","kddwwddddddwwddk","kddwwddddddwwddk","kddwwddddddwwddk","kddwwddddddwwddk","kddddwwddwwddddk","kddddwwddwwddddk","kddddddwwddddddk","kddddddwwddddddk","kddddddwwddddddk","kddddddwwddddddk","kddddddwwddddddk","kddddddwwddddddk","kddddddwwddddddk","kddddddwwddddddk","kkkkkkkkkkkkkkkk"],
ltr_Z:["kkkkkkkkkkkkkkkk","kHHwwwwwwwwwwHHk","kHHwwwwwwwwwwHHk","kHHHHHHHHHHwwHHk","kHHHHHHHHHHwwHHk","kHHHHHHHHwwHHHHk","kHHHHHHHHwwHHHHk","kHHHHHHwwHHHHHHk","kHHHHHHwwHHHHHHk","kHHHHwwHHHHHHHHk","kHHHHwwHHHHHHHHk","kHHwwHHHHHHHHHHk","kHHwwHHHHHHHHHHk","kHHwwwwwwwwwwHHk","kHHwwwwwwwwwwHHk","kkkkkkkkkkkkkkkk"]
};
function pixSVG(name,size,cls){
  const g=ICONS[name]||ICONS.info,S=16;let rects='';
  for(let y=0;y<g.length;y++){
    const row=g[y];let x=0;
    while(x<S){
      const ch=row[x]||' ';
      if(ch===' '||!IPAL[ch]){x++;continue;}
      let w=1;while(x+w<S&&row[x+w]===ch)w++;
      rects+=`<rect x="${x}" y="${y}" width="${w}" height="1" fill="${IPAL[ch]}"/>`;
      x+=w;
    }
  }
  return `<svg class="${cls||''}" width="${size||32}" height="${size||32}" viewBox="0 0 16 16" shape-rendering="crispEdges" xmlns="http://www.w3.org/2000/svg">${rects}</svg>`;
}
